import {Options} from './Options';

export class TemplateOptions {
  id?: string;
  label ?: string;
  placeholder ?: string;
  disabled ?: boolean;
  maxlength ?: number;
  minlength ?: number;
  placeholder_fr ?: string ;
  placeholder_ar ?: string ;
  pattern ?: RegExp | string;
  multiple ?: boolean;
  type ?: string;
  options?: string[];
  required?: boolean;
  hidden?: boolean;
  hide_label_fr ?: boolean;
  hide_label_ar ?: boolean;
  custom_css?: string;
  field_tags ?: string[];
  property_name ?:string;
  error_label ?: string;
  custom_error_message ?: string;
  number_rows ?: string;
  number_columns ?: string;
  theme ?: string;
  collapsible?: string;
  langue ?: string;
  label_fr ?: string;
  label_ar ?: string;
  tabs ?: { [key: string]: any } = {};
  steps ?: { [key: string]: any } = {};
  rows?: Array<Array<{ columns: any[] }>> = [];
  htmlElement ?: string;
  link_iframe ?: string;
  html_content ?: string;
  stepper_orientation ?: string;
  storageType ?: string;
  minFileSize ?: number;
  maxFileSize ?: number;
}
